// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockWorldID$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockWorldID";
  readonly sourceName: "contracts/MockWorldID.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"root","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"groupId","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"signalHash","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"nullifierHash","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"externalNullifierHash","type":"uint256"},{"indexed":false,"internalType":"bool","name":"success","type":"bool"}],"name":"VerificationAttempt","type":"event"},{"inputs":[{"internalType":"bool","name":"_shouldPass","type":"bool"}],"name":"setShouldPass","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"shouldPass","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"root","type":"uint256"},{"internalType":"uint256","name":"groupId","type":"uint256"},{"internalType":"uint256","name":"signalHash","type":"uint256"},{"internalType":"uint256","name":"nullifierHash","type":"uint256"},{"internalType":"uint256","name":"externalNullifierHash","type":"uint256"},{"internalType":"uint256[8]","name":"proof","type":"uint256[8]"}],"name":"verifyProof","outputs":[],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x6080806040523461002157600160ff195f5416175f5561015590816100268239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c9081633bc778e3146100905750806367607372146100625763eb5dd1e31461003d575f80fd5b3461005e575f36600319011261005e57602060ff5f54166040519015158152f35b5f80fd5b3461005e57602036600319011261005e5760043580151580910361005e5760ff80195f54169116175f555f80f35b3461005e576101a036600319011261005e57366101a41161005e5760ff5f5416156100b757005b62461bcd60e51b815260206004820152603a60248201527f4d6f636b576f726c6449443a20496e76616c69642070726f6f66206f7220696460448201527f656e7469747920766572696669636174696f6e206661696c65640000000000006064820152608490fdfea2646970667358221220fb589f53c95c7d30f996f332f78453eba1cc41caa5905a4309ec2045ad1adbb764736f6c63430008160033";
  readonly deployedBytecode: "0x6080806040526004361015610012575f80fd5b5f3560e01c9081633bc778e3146100905750806367607372146100625763eb5dd1e31461003d575f80fd5b3461005e575f36600319011261005e57602060ff5f54166040519015158152f35b5f80fd5b3461005e57602036600319011261005e5760043580151580910361005e5760ff80195f54169116175f555f80f35b3461005e576101a036600319011261005e57366101a41161005e5760ff5f5416156100b757005b62461bcd60e51b815260206004820152603a60248201527f4d6f636b576f726c6449443a20496e76616c69642070726f6f66206f7220696460448201527f656e7469747920766572696669636174696f6e206661696c65640000000000006064820152608490fdfea2646970667358221220fb589f53c95c7d30f996f332f78453eba1cc41caa5905a4309ec2045ad1adbb764736f6c63430008160033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/MockWorldID.sol";
  readonly buildInfoId: "solc-0_8_22-fb8d2fbb18579375ac6a74896a28503182f4525b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockWorldID"]: MockWorldID$Type;
    ["contracts/MockWorldID.sol:MockWorldID"]: MockWorldID$Type;
  }
}