import { logout } from '../services/auth.js';
import { getLang } from '../utils/i18n.js';

export function checkAndShowTermsModal(onAccept) {
  if (localStorage.getItem('blockdrop_terms_accepted') === 'true') {
    if (onAccept) onAccept();
    return;
  }

  // Create modal container
  const overlay = document.createElement('div');
  overlay.className = 'game-overlay';
  overlay.style.cssText = `
    position: fixed;
    inset: 0;
    background: rgba(10, 10, 26, 0.95);
    backdrop-filter: blur(15px);
    -webkit-backdrop-filter: blur(15px);
    z-index: 100000;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: var(--space-md);
  `;

  const lang = getLang();

  const title = lang === 'en' ? '⚖️ TERMS & PRIVACY' : '⚖️ TÉRMINOS Y PRIVACIDAD';
  const subtitle = lang === 'en' ? 'Please read and accept the terms to continue' : 'Por favor, lee y acepta los términos para continuar';
  
  const content = lang === 'en' ? `
        <h3 style="color: #fff; font-size: 0.95rem; margin-top: 0; font-family: var(--font-display);">1. ACCEPTANCE OF TERMS</h3>
        <p>By accessing and using BlockDrop, you agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree, you may not access the service or participate in the game dynamics.</p>
        
        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">2. GAME DESCRIPTION</h3>
        <p>BlockDrop is a skill-based web3 game. It features a DeFi reward pool system funded by users' staking contributions. The interest generated by this pool is distributed weekly among the top scores on the leaderboard.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">3. DEFI & CRYPTO RISKS</h3>
        <p>Interacting with smart contracts, Web3 wallets, and cryptocurrencies (such as USDC) carries inherent financial risks of capital loss, transaction errors, or network failures. BlockDrop is not responsible for financial losses caused by third-party technical failures or user negligence.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">4. HUMANITY VERIFICATION (WORLD ID)</h3>
        <p>To ensure fair competition free of bots and duplicate accounts, users in prize-eligible positions may require humanity verification via World ID. Failure to verify will result in ineligibility to collect the weekly DeFi prize.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">5. PRIVACY & DATA POLICY</h3>
        <p>To protect your privacy, we do not collect or store any sensitive civil identity data (such as names or phone numbers). We only store your public wallet address, optional social media information (Twitter/X, Discord, Telegram) voluntarily provided for task verification, and your game score for the ranking.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">6. MODIFICATIONS</h3>
        <p>BlockDrop reserves the right to modify these terms at any time. It is the user's responsibility to periodically review these policies. Continued use of the game implies unconditional acceptance of the new established terms.</p>
        
        <p style="margin-bottom: 0; font-weight: bold; color: var(--neon-cyan); text-align: center; margin-top: var(--space-lg);">🏆 YOU HAVE REACHED THE END! YOU CAN NOW ACCEPT THE TERMS.</p>
  ` : `
        <h3 style="color: #fff; font-size: 0.95rem; margin-top: 0; font-family: var(--font-display);">1. ACEPTACIÓN DE LOS TÉRMINOS</h3>
        <p>Al acceder y utilizar BlockDrop, usted acepta regirse por estos Términos y Condiciones y nuestra Política de Privacidad. Si no está de acuerdo, no podrá acceder al servicio ni participar en las dinámicas del juego.</p>
        
        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">2. DESCRIPCIÓN DEL JUEGO</h3>
        <p>BlockDrop es un juego de destreza web3 basado en Tetris. Cuenta con un sistema de pozo de recompensas DeFi financiado por los aportes de staking de los usuarios. Los intereses generados por dicho pool se distribuyen semanalmente entre los mejores puntajes del ranking.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">3. RIESGOS DEFI Y CRIPTOMONEDAS</h3>
        <p>La interacción con contratos inteligentes, billeteras Web3 y criptomonedas (tales como USDC) conlleva riesgos financieros inherentes de pérdida de capital, errores en transacciones o fallos de red. BlockDrop no se responsabiliza por pérdidas monetarias causadas por fallos técnicos de terceras partes o descuidos del usuario.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">4. VERIFICACIÓN DE HUMANIDAD (WORLD ID)</h3>
        <p>Para garantizar una competencia justa libre de bots y cuentas duplicadas, los usuarios en puestos elegibles para premios podrían requerir una verificación de humanidad mediante World ID. La falta de verificación resultará en la ineligibilidad para el cobro del premio DeFi semanal.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">5. POLÍTICA DE PRIVACIDAD Y DATOS</h3>
        <p>Para proteger su privacidad, no recopilamos ni almacenamos ningún dato sensible de identidad civil (como nombres o teléfonos). Almacenamos únicamente su dirección de billetera pública, información de redes sociales opcionales (Twitter/X, Discord, Telegram) aportadas de forma voluntaria para verificación de tareas, y su puntuación de juego para el ranking.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">6. MODIFICACIONES</h3>
        <p>BlockDrop se reserva el derecho de modificar estos términos en cualquier momento. Es responsabilidad del usuario revisar periódicamente estas políticas. El uso continuo del juego implica la aceptación incondicional de los nuevos términos establecidos.</p>
        
        <p style="margin-bottom: 0; font-weight: bold; color: var(--neon-cyan); text-align: center; margin-top: var(--space-lg);">🏆 ¡HAS LLEGADO AL FINAL! YA PUEDES ACEPTAR LOS TÉRMINOS.</p>
  `;

  const declineText = lang === 'en' ? '❌ Decline' : '❌ Rechazar';
  const acceptText = lang === 'en' ? '🛡️ Accept and Continue' : '🛡️ Aceptar y Continuar';

  overlay.innerHTML = `
    <div class="card card-glass" style="width: 100%; max-width: 550px; border: 1.5px solid var(--border-glow); box-shadow: var(--shadow-neon-purple); display: flex; flex-direction: column; gap: var(--space-md); padding: var(--space-lg); max-height: 90vh;">
      
      <div style="text-align: center; border-bottom: 1px solid var(--border-color); padding-bottom: var(--space-sm);">
        <h2 class="text-gradient" style="font-family: var(--font-display); font-size: 1.5rem; letter-spacing: 1px; margin: 0;">
          ${title}
        </h2>
        <p style="color: var(--text-secondary); font-size: 0.8rem; margin: 4px 0 0 0;">
          ${subtitle}
        </p>
      </div>

      <!-- Scrollable Terms Box -->
      <div id="terms-scroll-box" style="flex: 1; overflow-y: auto; padding: var(--space-md); background: rgba(0, 0, 0, 0.3); border: 1px solid var(--border-color); border-radius: var(--radius-md); font-size: 0.8rem; line-height: 1.6; color: var(--text-secondary); text-align: justify; max-height: 40vh;">
        ${content}
      </div>

      <!-- Action Buttons -->
      <div style="display: flex; gap: var(--space-md); width: 100%; margin-top: var(--space-sm);">
        <button class="btn btn-secondary" id="btn-terms-decline" style="flex: 1; font-size: 0.85rem; padding: 10px;">
          ${declineText}
        </button>
        <button class="btn btn-primary" id="btn-terms-accept" disabled style="flex: 1; font-size: 0.85rem; padding: 10px; opacity: 0.5; cursor: not-allowed; transition: all 0.2s ease;">
          ${acceptText}
        </button>
      </div>
    </div>
  `;

  document.body.appendChild(overlay);

  const scrollBox = overlay.querySelector('#terms-scroll-box');
  const acceptBtn = overlay.querySelector('#btn-terms-accept');
  const declineBtn = overlay.querySelector('#btn-terms-decline');

  // Scroll listener to activate the Accept button
  const checkScroll = () => {
    if (!scrollBox || !acceptBtn) return;
    const threshold = 10; //px from bottom
    const isAtBottom = scrollBox.scrollHeight - scrollBox.scrollTop <= scrollBox.clientHeight + threshold;
    if (isAtBottom) {
      acceptBtn.disabled = false;
      acceptBtn.style.opacity = '1';
      acceptBtn.style.cursor = 'pointer';
      acceptBtn.style.boxShadow = 'var(--shadow-neon-cyan)';
    }
  };

  scrollBox.addEventListener('scroll', checkScroll);
  // Also check if text is already completely visible (small screens/resolutions)
  setTimeout(checkScroll, 300);

  // Decline action
  declineBtn.addEventListener('click', () => {
    overlay.remove();
    logout();
    window.location.hash = '#/auth';
  });

  // Accept action
  acceptBtn.addEventListener('click', () => {
    localStorage.setItem('blockdrop_terms_accepted', 'true');
    overlay.remove();
    if (onAccept) onAccept();
  });
}

export function showTermsOnlyModal() {
  // Create view-only modal for footer link clicks
  const overlay = document.createElement('div');
  overlay.className = 'game-overlay';
  overlay.style.cssText = `
    position: fixed;
    inset: 0;
    background: rgba(10, 10, 26, 0.95);
    backdrop-filter: blur(15px);
    -webkit-backdrop-filter: blur(15px);
    z-index: 100000;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: var(--space-md);
  `;

  const lang = getLang();
  
  const title = lang === 'en' ? '⚖️ TERMS & PRIVACY' : '⚖️ TÉRMINOS Y PRIVACIDAD';
  
  const content = lang === 'en' ? `
        <h3 style="color: #fff; font-size: 0.95rem; margin-top: 0; font-family: var(--font-display);">1. ACCEPTANCE OF TERMS</h3>
        <p>By accessing and using FrexLand, you agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree, you may not access the service.</p>
        
        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">2. GAME DESCRIPTION</h3>
        <p>FrexLand is a cross-platform web3 arcade portal. It features a DeFi reward pool system funded by users' staking contributions. The interest generated by this pool is distributed weekly among the top scores on the leaderboard.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">3. DEFI & CRYPTO RISKS</h3>
        <p>Interacting with smart contracts, Web3 wallets, and cryptocurrencies (such as USDC) carries inherent financial risks of capital loss, transaction errors, or network failures. FrexLand is not responsible for financial losses caused by third-party technical failures or user negligence.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">4. HUMANITY VERIFICATION (WORLD ID)</h3>
        <p>To ensure fair competition free of bots and duplicate accounts, users in prize-eligible positions may require humanity verification via World ID. Failure to verify will result in ineligibility to collect the weekly DeFi prize.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">5. PRIVACY & DATA POLICY</h3>
        <p>To protect your privacy, we do not collect or store any sensitive civil identity data (such as names or phone numbers). We only store your public wallet address, optional social media information (Twitter/X, Discord, Telegram) voluntarily provided for task verification, and your game score for the ranking.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">6. MODIFICATIONS</h3>
        <p>FrexLand reserves the right to modify these terms at any time. It is the user's responsibility to periodically review these policies. Continued use of the game implies unconditional acceptance of the new established terms.</p>
  ` : `
        <h3 style="color: #fff; font-size: 0.95rem; margin-top: 0; font-family: var(--font-display);">1. ACEPTACIÓN DE LOS TÉRMINOS</h3>
        <p>Al acceder y utilizar FrexLand, usted acepta regirse por estos Términos y Condiciones y nuestra Política de Privacidad. Si no está de acuerdo, no podrá acceder al servicio.</p>
        
        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">2. DESCRIPCIÓN DEL JUEGO</h3>
        <p>FrexLand es un portal arcade web3 multiplataforma. Cuenta con un sistema de pozo de recompensas DeFi financiado por los aportes de staking de los usuarios. Los intereses generados por dicho pool se distribuyen semanalmente entre los mejores puntajes del ranking.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">3. RIESGOS DEFI Y CRIPTOMONEDAS</h3>
        <p>La interacción con contratos inteligentes, billeteras Web3 y criptomonedas (tales como USDC) conlleva riesgos financieros inherentes de pérdida de capital, errores en transacciones o fallos de red. FrexLand no se responsabiliza por pérdidas monetarias causadas por fallos técnicos de terceras partes o descuidos del usuario.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">4. VERIFICACIÓN DE HUMANIDAD (WORLD ID)</h3>
        <p>Para garantizar una competencia justa libre de bots y cuentas duplicadas, los usuarios en puestos elegibles para premios podrían requerir una verificación de humanidad mediante World ID. La falta de verificación resultará en la ineligibilidad para el cobro del premio DeFi semanal.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">5. POLÍTICA DE PRIVACIDAD Y DATOS</h3>
        <p>Para proteger su privacidad, no recopilamos ni almacenamos ningún dato sensible de identidad civil (como nombres o teléfonos). Almacenamos únicamente su dirección de billetera pública, información de redes sociales opcionales (Twitter/X, Discord, Telegram) aportadas de forma voluntaria para verificación de tareas, y su puntuación de juego para el ranking.</p>

        <h3 style="color: #fff; font-size: 0.95rem; margin-top: var(--space-md); font-family: var(--font-display);">6. MODIFICACIONES</h3>
        <p>FrexLand se reserva el derecho de modificar estos términos en cualquier momento. Es responsabilidad del usuario revisar periódicamente estas políticas. El uso continuo del juego implica la aceptación incondicional de los nuevos términos establecidos.</p>
  `;
  
  const okText = lang === 'en' ? 'Understood' : 'Entendido';

  overlay.innerHTML = `
    <div class="card card-glass" style="width: 100%; max-width: 550px; border: 1.5px solid var(--border-glow); box-shadow: var(--shadow-neon-purple); display: flex; flex-direction: column; gap: var(--space-md); padding: var(--space-lg); max-height: 90vh; position: relative;">
      
      <button id="btn-terms-close" style="position: absolute; top: 15px; right: 15px; background: transparent; border: none; color: var(--text-muted); font-size: 1.25rem; cursor: pointer; hover: color: #fff;">✕</button>

      <div style="text-align: center; border-bottom: 1px solid var(--border-color); padding-bottom: var(--space-sm);">
        <h2 class="text-gradient" style="font-family: var(--font-display); font-size: 1.5rem; letter-spacing: 1px; margin: 0;">
          ${title}
        </h2>
      </div>

      <!-- Scrollable Terms Box -->
      <div style="flex: 1; overflow-y: auto; padding: var(--space-md); background: rgba(0, 0, 0, 0.3); border: 1px solid var(--border-color); border-radius: var(--radius-md); font-size: 0.85rem; line-height: 1.6; color: var(--text-secondary); text-align: justify; max-height: 50vh;">
        ${content}
      </div>

      <div style="width: 100%; text-align: center; margin-top: var(--space-sm);">
        <button class="btn btn-primary" id="btn-terms-ok" style="width: 100%; max-width: 200px; font-size: 0.85rem; padding: 10px;">
          ${okText}
        </button>
      </div>

    </div>
  `;

  document.body.appendChild(overlay);

  const closeBtn = overlay.querySelector('#btn-terms-close');
  const okBtn = overlay.querySelector('#btn-terms-ok');

  const close = () => overlay.remove();
  closeBtn.addEventListener('click', close);
  okBtn.addEventListener('click', close);
}
