// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface TetrisAaveProxy$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "TetrisAaveProxy";
  readonly sourceName: "contracts/TetrisAaveProxy.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"_logic","type":"address"},{"internalType":"bytes","name":"_data","type":"bytes"}],"stateMutability":"payable","type":"constructor"},{"inputs":[{"internalType":"address","name":"target","type":"address"}],"name":"AddressEmptyCode","type":"error"},{"inputs":[{"internalType":"address","name":"implementation","type":"address"}],"name":"ERC1967InvalidImplementation","type":"error"},{"inputs":[],"name":"ERC1967NonPayable","type":"error"},{"inputs":[],"name":"ERC1967ProxyUninitialized","type":"error"},{"inputs":[],"name":"FailedCall","type":"error"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"implementation","type":"address"}],"name":"Upgraded","type":"event"},{"stateMutability":"payable","type":"fallback"}];
  readonly bytecode: "0x6040608081526102c5803803806100158161018c565b928339810182828203126101745781516001600160a01b038116928382036101745760208181015190916001600160401b039190828211610174570184601f8201121561017457805191821161017857610077601f8301601f1916840161018c565b94828652838383010111610174575f5b828110610161575050905f918401015281511561015057803b15610138577f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc80546001600160a01b031916841790558351927fbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b5f80a281511561011c5761010e92506101b1565b505b51608290816102438239f35b5050346101295750610110565b63b398979f60e01b8152600490fd5b8351634c9c8ce360e01b815260048101849052602490fd5b83516330a289cf60e21b8152600490fd5b8181018401518682018501528301610087565b5f80fd5b634e487b7160e01b5f52604160045260245ffd5b6040519190601f01601f191682016001600160401b0381118382101761017857604052565b905f8091602081519101845af4808061022f575b156101e55750506040513d81523d5f602083013e60203d82010160405290565b1561020c57604051639996b31560e01b81526001600160a01b039091166004820152602490fd5b3d1561021d576040513d5f823e3d90fd5b60405163d6bda27560e01b8152600490fd5b503d1515806101c55750813b15156101c556fe60806040527f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc545f9081906001600160a01b0316368280378136915af43d5f803e156048573d5ff35b3d5ffdfea2646970667358221220d337d0233d6e56c8625e81cf58152bdf948cb943f30460cfc1bb51d30284fad164736f6c63430008160033";
  readonly deployedBytecode: "0x60806040527f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc545f9081906001600160a01b0316368280378136915af43d5f803e156048573d5ff35b3d5ffdfea2646970667358221220d337d0233d6e56c8625e81cf58152bdf948cb943f30460cfc1bb51d30284fad164736f6c63430008160033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/TetrisAaveProxy.sol";
  readonly buildInfoId: "solc-0_8_22-fb8d2fbb18579375ac6a74896a28503182f4525b";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["TetrisAaveProxy"]: TetrisAaveProxy$Type;
    ["contracts/TetrisAaveProxy.sol:TetrisAaveProxy"]: TetrisAaveProxy$Type;
  }
}